# values.yaml
global:
  environment: production

# Linkerd configuration should be at root level
linkerd:
  enabled: true

minio:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi  # Now properly under persistence
    storageClass: "standard"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  service:
    type: ClusterIP
    apiPort: 9000
    consolePort: 9001
  credentials:
    existingSecret: "file-server-minio-secret"
    accessKeyKey: "access-key"
    secretKeyKey: "secret-key"
  bucket:
    name: "up42-storage"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      labels:
        release: prometheus
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9000"

s3www:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  replicaCount: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "200m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  service:
    type: ClusterIP   #LoadBalancer
    port: 80
    annotations: {}
  # Remove the linkerd section from here too
  ingress:
    enabled: false
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: file-server.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      labels:
        release: prometheus
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"

podDisruptionBudget:
  enabled: true
  minAvailable: 1

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - s3www
        topologyKey: "kubernetes.io/hostname"
